name: CI

on:
  push:
    branches:
      - master  # Specify the branch where you want tests to run
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Updated to use v2, which is more stable than v1

      - name: Set up Python 2.7
        uses: MatteoH2O1999/setup-python@v1
        with:
          python-version: 2.7
          allow-build: info
          cache-build: true
          cache: pip

      - name: Install dependencies
        run: pip install pygame

      - name: Install more dependencies
        run: pip install mock

      - name: Install even more dependencies
        run: pip install pyinstaller==3.6

      - name: Install xmllint
        run: sudo apt-get install -y python-dev

      - name: Run tests
        run: python test_sm.py  # Replace with your test command

      - name: Build Executable
        run: |
          pyinstaller --onefile contact_manager_solution.py
          # Create the "artifacts" directory if it doesn't exist
          mkdir -p artifacts
          # Move the executable to the "artifacts" directory
          mv dist/contact_manager_solution artifacts/

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3  # Corrected to use v3
        with:
          name: ContactManagerPython2
          path: artifacts
